//
// DO NOT EDIT THIS FILE.Generated using AndroidAnnotations 3.3.2.
//  You can create a larger work that contains this file and distribute that work under terms of your choice.
//


package cn.hi028.android.highcommunity.activity.fragment;

import android.os.Bundle;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.FrameLayout;
import android.widget.TextView;
import cn.hi028.android.highcommunity.R.layout;
import net.duohuo.dhroid.view.CustomListView;
import org.androidannotations.api.builder.FragmentBuilder;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;

public final class HuiChipOrderDetailFrag_
    extends cn.hi028.android.highcommunity.activity.fragment.HuiChipOrderDetailFrag
    implements HasViews, OnViewChangedListener
{

    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();
    private View contentView_;

    @Override
    public void onCreate(Bundle savedInstanceState) {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
    }

    @Override
    public View findViewById(int id) {
        if (contentView_ == null) {
            return null;
        }
        return contentView_.findViewById(id);
    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        contentView_ = super.onCreateView(inflater, container, savedInstanceState);
        if (contentView_ == null) {
            contentView_ = inflater.inflate(layout.frag_hlife_order_detail, container, false);
        }
        return contentView_;
    }

    @Override
    public void onDestroyView() {
        contentView_ = null;
        super.onDestroyView();
    }

    private void init_(Bundle savedInstanceState) {
        OnViewChangedNotifier.registerOnViewChangedListener(this);
    }

    @Override
    public void onViewCreated(View view, Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    public static HuiChipOrderDetailFrag_.FragmentBuilder_ builder() {
        return new HuiChipOrderDetailFrag_.FragmentBuilder_();
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        tv_reserve_address = ((TextView) hasViews.findViewById(cn.hi028.android.highcommunity.R.id.tv_reserve_address));
        fl_order_op = ((FrameLayout) hasViews.findViewById(cn.hi028.android.highcommunity.R.id.fl_order_op));
        tv_order_operate2 = ((TextView) hasViews.findViewById(cn.hi028.android.highcommunity.R.id.tv_order_operate2));
        tv_order_time = ((TextView) hasViews.findViewById(cn.hi028.android.highcommunity.R.id.tv_order_time));
        ll_NoticeDetails_Progress = hasViews.findViewById(cn.hi028.android.highcommunity.R.id.ll_NoticeDetails_Progress);
        tv_order_id = ((TextView) hasViews.findViewById(cn.hi028.android.highcommunity.R.id.tv_order_id));
        tv_reserve_name = ((TextView) hasViews.findViewById(cn.hi028.android.highcommunity.R.id.tv_reserve_name));
        tv_coupon = ((TextView) hasViews.findViewById(cn.hi028.android.highcommunity.R.id.tv_coupon));
        tv_reserve_wallet = ((TextView) hasViews.findViewById(cn.hi028.android.highcommunity.R.id.tv_reserve_wallet));
        tv_reserve_phone = ((TextView) hasViews.findViewById(cn.hi028.android.highcommunity.R.id.tv_reserve_phone));
        tv_price = ((TextView) hasViews.findViewById(cn.hi028.android.highcommunity.R.id.tv_price));
        cl_goods = ((CustomListView) hasViews.findViewById(cn.hi028.android.highcommunity.R.id.cl_goods));
        tv_order_operate1 = ((TextView) hasViews.findViewById(cn.hi028.android.highcommunity.R.id.tv_order_operate1));
        tv_total_pay = ((TextView) hasViews.findViewById(cn.hi028.android.highcommunity.R.id.tv_total_pay));
        initView();
    }

    public static class FragmentBuilder_
        extends FragmentBuilder<HuiChipOrderDetailFrag_.FragmentBuilder_, cn.hi028.android.highcommunity.activity.fragment.HuiChipOrderDetailFrag>
    {


        @Override
        public cn.hi028.android.highcommunity.activity.fragment.HuiChipOrderDetailFrag build() {
            HuiChipOrderDetailFrag_ fragment_ = new HuiChipOrderDetailFrag_();
            fragment_.setArguments(args);
            return fragment_;
        }

    }

}
