//
// DO NOT EDIT THIS FILE.Generated using AndroidAnnotations 3.3.2.
//  You can create a larger work that contains this file and distribute that work under terms of your choice.
//


package cn.hi028.android.highcommunity.activity.fragment;

import android.os.Bundle;
import android.support.v4.view.ViewPager;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.RadioGroup;
import cn.hi028.android.highcommunity.R.layout;
import org.androidannotations.api.builder.FragmentBuilder;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;

public final class MyCollectionSwitchFrag_
    extends cn.hi028.android.highcommunity.activity.fragment.MyCollectionSwitchFrag
    implements HasViews, OnViewChangedListener
{

    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();
    private View contentView_;

    @Override
    public void onCreate(Bundle savedInstanceState) {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
    }

    @Override
    public View findViewById(int id) {
        if (contentView_ == null) {
            return null;
        }
        return contentView_.findViewById(id);
    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        contentView_ = super.onCreateView(inflater, container, savedInstanceState);
        if (contentView_ == null) {
            contentView_ = inflater.inflate(layout.frag_mycollectionswitch, container, false);
        }
        return contentView_;
    }

    @Override
    public void onDestroyView() {
        contentView_ = null;
        super.onDestroyView();
    }

    private void init_(Bundle savedInstanceState) {
        OnViewChangedNotifier.registerOnViewChangedListener(this);
    }

    @Override
    public void onViewCreated(View view, Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    public static MyCollectionSwitchFrag_.FragmentBuilder_ builder() {
        return new MyCollectionSwitchFrag_.FragmentBuilder_();
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        mRadioGroup = ((RadioGroup) hasViews.findViewById(cn.hi028.android.highcommunity.R.id.rg_MyCollectionSwitch));
        mViewPager = ((ViewPager) hasViews.findViewById(cn.hi028.android.highcommunity.R.id.vp_MyCollectionSwitch_viewpager));
        initView();
    }

    public static class FragmentBuilder_
        extends FragmentBuilder<MyCollectionSwitchFrag_.FragmentBuilder_, cn.hi028.android.highcommunity.activity.fragment.MyCollectionSwitchFrag>
    {


        @Override
        public cn.hi028.android.highcommunity.activity.fragment.MyCollectionSwitchFrag build() {
            MyCollectionSwitchFrag_ fragment_ = new MyCollectionSwitchFrag_();
            fragment_.setArguments(args);
            return fragment_;
        }

    }

}
